version: '3.8'
# For Local Development Only
services:
  db:
    container_name: db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: keystone
      POSTGRES_PASSWORD: keystonecms
      POSTGRES_DB: keystone
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local