name: Portal Client Docker Build Cache and Save Artifact

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md**'
    branches: [main]

jobs:
  build-and-cache-portal-client:
      uses: USSF-ORBIT/ussf-portal/.github/workflows/build-and-cache-portal-client.yml@docker-ci/minhlai/re-usable-docker-cache-workflows
