name: Keystone CMS Docker Build and Save Cache

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md**'
    branches: [main]

jobs:
  build-and-cache-keystone-cms:
      uses: USSF-ORBIT/ussf-portal/.github/workflows/reusable-docker-cache-keystone-cms.yml@docker-ci/minhlai/re-usable-docker-cache-workflows

  trigger-build-and-cache-in-cms-repo:
      runs-on: ubuntu-latest
      steps:
        - name: call GH API to trigger workflow
          run: gh workflow run build-keystone-cms-docker-cache.yml -R USSF-ORBIT/ussf-portal-client --ref docker-ci/minhlai/re-use-docker-cache-workflows
          env:
            GH_TOKEN: ${{secrets.PUBLIC_REPO_READ}} 
