name: Docker Build Cache Save Artifact

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md**'
    branches: [main]

jobs:
  build-and-save-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Docker Buildx
        uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1 # v2
        id: buildx
        with:
          install: true

      - name: Build Keystone to e2e Stage
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4
        with:
          context: .
          tags: keystone-cms:e2e
          cache-to: type=local,mode=max,dest=/tmp/keystone-cms,tag=e2e,compression=estargz,compression-level=9
          target: e2e

      - name: Upload keystone-cms cache directory
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: keystone-cms
          path: /tmp/keystone-cms

      - name: Upload portal-client manifest
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: keystone-cms-index
          path: /tmp/keystone-cms/index.json

      - name: Get docker image digest from manifest
        id: manifest
        run: |
          digest=$(cat /tmp/keystone-cms/index.json | jq -r '.manifests[0].digest')
          echo "docker_tag=${digest##sha256:}" >> $GITHUB_OUTPUT

      - name: Save docker cache to GHA cache using image digest as key
        uses: actions/cache/save@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: /tmp/keystone-cms
          key: ${{ runner.os }}-docker-keystone-cms-${{ steps.manifest.outputs.docker_tag }}
