name: Docker Build Test

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md**'
    branches: [main]
  workflow_dispatch:

jobs:
  check-docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Restore keystone cms Docker build cache
        uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        id: restore-keystone-cache
        with:
          path: /tmp/portal-client
          key: ${{ runner.os }}-docker-keystone-cms
          restore-keys: ${{ runner.os }}-docker-keystone-cms

      - uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1 # v2
        id: buildx
        with:
          install: true

      - name: Add DoD Certificate Bundle
        env:
          CERT_BUNDLE_SHA256: ${{ secrets.DOD_CA_CERT_BUNDLE_SHA256 }}
        run: |
          echo "$CERT_BUNDLE_SHA256" > scripts/dod_ca_cert_bundle.sha256
          sudo bash scripts/add-dod-cas.sh

      - name: Build
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4
        with:
          context: .
          push: false
          tags: portal-client:${{ github.sha }}
          build-args: |
            BUILD=${{ github.sha }}
          cache-from: |
            type=local,src=/tmp/portal-client,tag=e2e
