name: Cypress E2E tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up node
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # tag=v3
        with:
          node-version: '14.19.0'

      - name: Check out repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          path: ./ussf-portal-cms

      - name: Build image for testing
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: docker build -t $IMAGE_TAG --target e2e .
        working-directory: ./ussf-portal-cms

      - name: Check out portal client
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          repository: USSF-ORBIT/ussf-portal-client
          ref: 340-shared-session # TODO remove after merged
          path: ./ussf-portal-client

      - name: Build image for testing
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: docker build -t $IMAGE_TAG .
        working-directory: ./ussf-portal-cms

      - name: Echo docker config
        run: docker-compose config
        working-directory: ./ussf-portal-cms

      - name: Docker compose
        run: docker-compose up -d
        working-directory: ./ussf-portal-cms
        env:
          IMAGE_TAG: ${{ github.sha }}

      - name: Docker logs
        uses: jwalton/gh-docker-logs@v2.2.0
        with:
          dest: './ussf-portal-cms/logs'

      - name: Cypress run
        uses: cypress-io/github-action@90f0f494f47dd0a22ac4759978de892d3e3fd340 # tag=v3.0.2
        env:
          CYPRESS_BASE_URL: http://localhost:3001
          CYPRESS_TEST_PASSWORD: adminpassword
          CYPRESS_TEST_EMAIL: admin@example.com
        with:
          install-command: yarn install --frozen-lockfile
          working-directory: ./ussf-portal-cms/e2e

      - name: Upload logs
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3
        if: always()
        with:
          name: container-logs
          path: ussf-portal-cms/logs

      - name: Upload screenshots
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3
        if: failure()
        with:
          name: cypress-screenshots
          path: ussf-portal-cms/e2e/cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3
        if: always()
        with:
          name: cypress-videos
          path: ussf-portal-cms/e2e/cypress/videos

      - name: Upload reports
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3
        if: always()
        with:
          name: cypress-reports
          path: ussf-portal-cms/e2e/cypress/reports
