name: Node CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md**'
    branches: [main]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md**'
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Read Node.js version from package.json
        run: echo "nodeVersion=$(node -p "require('./package.json').engines.node")" >> $GITHUB_OUTPUT
        id: engines

      - name: Set up node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: ${{ steps.engines.outputs.nodeVersion }}

      - name: Start Database
        run: |
          docker run --rm --detach \
            --publish '5432:5432' \
            --env POSTGRES_PASSWORD=keystonecms \
            --env POSTGRES_USER=keystone \
            --env POSTGRES_DB=unit-test postgres:14.3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ steps.yarn-cache-dir-path.outputs.dir }}

      # The yarn cache is not node_modules
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint code
        run: yarn lint

      - name: Run Jest tests
        run: yarn test --coverage
